version: '2'

networks:
  zentao-net:
    driver: bridge

services:

# mysql service for zentao
  zentao-mysql:
    image: mysql:5.7
    container_name: zentao-mysql
    ports:
      - '3307:3306'
    volumes:
      - 'zentao_db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=pass4Zentao
      - MYSQL_DATABASE=zentao
    networks:
      - zentao-net

# zentao service
  zentao:
    image: hub.qucheng.com/app/quickon-zentao:${TAG:-latest}
    container_name: zentao
    ports:
      - '8080:80'
    volumes:
      - 'zentao_data:/data'
    depends_on:
      - zentao-mysql
    environment:
      - MYSQL_HOST=zentao-mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass4Zentao
      - MYSQL_DB=zentao
      - PHP_MAX_EXECUTION_TIME=120
      - PHP_MEMORY_LIMIT=512M
      - PHP_POST_MAX_SIZE=128M
      - PHP_UPLOAD_MAX_FILESIZE=128M
      - LDAP_ENABLED=true
        #- EASYSOFT_DEBUG=true
        #- DEBUG=1
      - IS_CONTAINER=true
    networks:
      - zentao-net

# persistence for mysql and zentao
volumes:
  zentao_db:
    driver: local
  zentao_data:
    driver: local
