version: '2'

networks:
  zentao-net:
    driver: bridge

services:

# mysql service for zentao
  zentao-mysql:
    image: mysql:5.7
    container_name: zentao-mysql
    ports:
      - '3307:3306'
    volumes:
      - 'zentao_db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=pass4Zentao
      - MYSQL_DATABASE=zentao
    networks:
      - zentao-net

# zentao service
  zentao:
    image: hub.qucheng.com/app/quickon-zentao:${TAG:-latest}
    container_name: zentao
    ports:
      - '8080:80'
    volumes:
      - 'zentao_data:/data'
    depends_on:
      - zentao-mysql
    environment:
      - MYSQL_HOST=zentao-mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass4Zentao
      - MYSQL_DB=zentao
      - PHP_MAX_EXECUTION_TIME=120
      - PHP_MEMORY_LIMIT=512M
      - PHP_POST_MAX_SIZE=128M
      - PHP_UPLOAD_MAX_FILESIZE=128M
      - LDAP_ENABLED=false
      - SMTP_ENABLED=false
      - SMTP_FROMNAME=禅道旗舰版
      - SMTP_HOST=192.168.50.182
      - SMTP_PORT=25
      - SMTP_USER=root@demo.com
      - SMTP_PASS=password
      - APP_DEFAULT_PORT=80
      - APP_DOMAIN=zentao.demo.com
      - PROTOCOL_TYPE=http
      - EASYSOFT_DEBUG=true
      - DEBUG=1
      - IS_CONTAINER=true
      - LINK_GIT=false
      - GIT_TYPE=gitea
      - GIT_INSTANCE_NAME=demo
      - GIT_USERNAME=user
      - GIT_PASSWORD=password
      - GIT_DOMAIN=https://git.demo.com
      # - GIT_TOKEN=token-example
      - LINK_CI=false
      - CI_TYPE=jenkins
      - CI_URL=https://jenkins.demo.com
      - CI_USERNAME=user
      - CI_PASSWORD=password
      # - CI_TOKEN=token-example
      - LINK_SCAN=false
      - SCAN_TYPE=sonarqube
      - SCAN_URL=https://sonarqube.demo.com
      - SCAN_USERNAME=user
      - SCAN_PASSWORD=password
    networks:
      - zentao-net

# persistence for mysql and zentao
volumes:
  zentao_db:
    driver: local
  zentao_data:
    driver: local
